// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
  "aws_appsync_graphqlEndpoint": "https://ksr5z3w5x5c3rdmsnm3uceqcvi.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-northeast-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-ljfkpkvyrnasvappfbrep6x4pe",
};

export default awsmobile;
