// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
  "aws_appsync_graphqlEndpoint": "https://doqdoe24tjf2jinauffdgtqhne.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-northeast-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-vwyaecyaine5jhopcspilidieu",
};

export default awsmobile;
